### 
POST http://localhost:5001/users/add 
Content-Type: application/json

{
"username": "Jacob",
"score": 100
}

### 
POST https://test-leaderboard-56sk1urvm-mkuhn0411.vercel.app/users/add 
Content-Type: application/json

{
"username": "Jacob",
"score": 100
}