###
GET http://localhost:5002/users

### 
POST http://localhost:5002/users/add 
Content-Type: application/json

{
"username": "Jacob",
"score": 100
}

### 
POST https://test-leaderboard-ofrdnryoi-mkuhn0411.vercel.app/users/add 
Content-Type: application/json

{
"username": "Jacob",
"score": 100
}
